// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.htzhu.protobuf.routeguice;

public interface FeatureDatabaseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:com.htzhu.protobuf.routeguice.FeatureDatabase)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>repeated .com.htzhu.protobuf.routeguice.Feature feature = 1;</code>
	 */
	java.util.List<com.htzhu.protobuf.routeguice.Feature>
	getFeatureList();

	/**
	 * <code>repeated .com.htzhu.protobuf.routeguice.Feature feature = 1;</code>
	 */
	com.htzhu.protobuf.routeguice.Feature getFeature(int index);

	/**
	 * <code>repeated .com.htzhu.protobuf.routeguice.Feature feature = 1;</code>
	 */
	int getFeatureCount();

	/**
	 * <code>repeated .com.htzhu.protobuf.routeguice.Feature feature = 1;</code>
	 */
	java.util.List<? extends com.htzhu.protobuf.routeguice.FeatureOrBuilder>
	getFeatureOrBuilderList();

	/**
	 * <code>repeated .com.htzhu.protobuf.routeguice.Feature feature = 1;</code>
	 */
	com.htzhu.protobuf.routeguice.FeatureOrBuilder getFeatureOrBuilder(
			int index);
}
