// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.htzhu.protobuf.routeguice;

public interface RectangleOrBuilder extends
		// @@protoc_insertion_point(interface_extends:com.htzhu.protobuf.routeguice.Rectangle)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <pre>
	 * One corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point lo = 1;</code>
	 */
	boolean hasLo();

	/**
	 * <pre>
	 * One corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point lo = 1;</code>
	 */
	com.htzhu.protobuf.routeguice.Point getLo();

	/**
	 * <pre>
	 * One corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point lo = 1;</code>
	 */
	com.htzhu.protobuf.routeguice.PointOrBuilder getLoOrBuilder();

	/**
	 * <pre>
	 * The other corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point hi = 2;</code>
	 */
	boolean hasHi();

	/**
	 * <pre>
	 * The other corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point hi = 2;</code>
	 */
	com.htzhu.protobuf.routeguice.Point getHi();

	/**
	 * <pre>
	 * The other corner of the rectangle.
	 * </pre>
	 *
	 * <code>.com.htzhu.protobuf.routeguice.Point hi = 2;</code>
	 */
	com.htzhu.protobuf.routeguice.PointOrBuilder getHiOrBuilder();
}
