// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonProtos.proto

package com.htzhu.protobuf;

public final class PersonProtos {

	private PersonProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface PersonOrBuilder extends
			// @@protoc_insertion_point(interface_extends:Person)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string name = 1;</code>
		 */
		String getName();

		/**
		 * <code>string name = 1;</code>
		 */
		com.google.protobuf.ByteString
		getNameBytes();

		/**
		 * <code>int32 id = 2;</code>
		 */
		int getId();

		/**
		 * <code>string email = 3;</code>
		 */
		String getEmail();

		/**
		 * <code>string email = 3;</code>
		 */
		com.google.protobuf.ByteString
		getEmailBytes();

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		boolean hasPhone();

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		PersonProtos.Person.PhoneNumber getPhone();

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		PersonProtos.Person.PhoneNumberOrBuilder getPhoneOrBuilder();
	}

	/**
	 * Protobuf type {@code Person}
	 */
	public static final class Person extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:Person)
			PersonOrBuilder {

		private static final long serialVersionUID = 0L;

		// Use Person.newBuilder() to construct.
		private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Person() {
			name_ = "";
			id_ = 0;
			email_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private Person(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							String s = input.readStringRequireUtf8();

							name_ = s;
							break;
						}
						case 16: {

							id_ = input.readInt32();
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							email_ = s;
							break;
						}
						case 34: {
							PersonProtos.Person.PhoneNumber.Builder subBuilder = null;
							if (phone_ != null) {
								subBuilder = phone_.toBuilder();
							}
							phone_ = input.readMessage(PersonProtos.Person.PhoneNumber.parser(),
									extensionRegistry);
							if (subBuilder != null) {
								subBuilder.mergeFrom(phone_);
								phone_ = subBuilder.buildPartial();
							}

							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return PersonProtos.internal_static_Person_descriptor;
		}

		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return PersonProtos.internal_static_Person_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							PersonProtos.Person.class, PersonProtos.Person.Builder.class);
		}

		/**
		 * Protobuf enum {@code Person.PhoneType}
		 */
		public enum PhoneType
				implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MOBILE = 0;</code>
			 */
			MOBILE(0),
			/**
			 * <code>HOME = 1;</code>
			 */
			HOME(1),
			/**
			 * <code>WORK = 2;</code>
			 */
			WORK(2),
			UNRECOGNIZED(-1),;

			/**
			 * <code>MOBILE = 0;</code>
			 */
			public static final int MOBILE_VALUE = 0;
			/**
			 * <code>HOME = 1;</code>
			 */
			public static final int HOME_VALUE = 1;
			/**
			 * <code>WORK = 2;</code>
			 */
			public static final int WORK_VALUE = 2;


			public final int getNumber() {
				if (this == UNRECOGNIZED) {
					throw new IllegalArgumentException(
							"Can't get the number of an unknown enum value.");
				}
				return value;
			}

			/**
			 * @deprecated Use {@link #forNumber(int)} instead.
			 */
			@Deprecated
			public static PhoneType valueOf(int value) {
				return forNumber(value);
			}

			public static PhoneType forNumber(int value) {
				switch (value) {
					case 0:
						return MOBILE;
					case 1:
						return HOME;
					case 2:
						return WORK;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
			internalGetValueMap() {
				return internalValueMap;
			}

			private static final com.google.protobuf.Internal.EnumLiteMap<
					PhoneType> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
						public PhoneType findValueByNumber(int number) {
							return PhoneType.forNumber(number);
						}
					};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
			getValueDescriptor() {
				return getDescriptor().getValues().get(ordinal());
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptor() {
				return PersonProtos.Person.getDescriptor().getEnumTypes().get(0);
			}

			private static final PhoneType[] VALUES = values();

			public static PhoneType valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				if (desc.getIndex() == -1) {
					return UNRECOGNIZED;
				}
				return VALUES[desc.getIndex()];
			}

			private final int value;

			private PhoneType(int value) {
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:Person.PhoneType)
		}

		public interface PhoneNumberOrBuilder extends
				// @@protoc_insertion_point(interface_extends:Person.PhoneNumber)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>string number = 1;</code>
			 */
			String getNumber();

			/**
			 * <code>string number = 1;</code>
			 */
			com.google.protobuf.ByteString
			getNumberBytes();

			/**
			 * <code>.Person.PhoneType type = 2;</code>
			 */
			int getTypeValue();

			/**
			 * <code>.Person.PhoneType type = 2;</code>
			 */
			PersonProtos.Person.PhoneType getType();
		}

		/**
		 * Protobuf type {@code Person.PhoneNumber}
		 */
		public static final class PhoneNumber extends
				com.google.protobuf.GeneratedMessageV3 implements
				// @@protoc_insertion_point(message_implements:Person.PhoneNumber)
				PhoneNumberOrBuilder {

			private static final long serialVersionUID = 0L;

			// Use PhoneNumber.newBuilder() to construct.
			private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			private PhoneNumber() {
				number_ = "";
				type_ = 0;
			}

			@Override
			public final com.google.protobuf.UnknownFieldSet
			getUnknownFields() {
				return this.unknownFields;
			}

			private PhoneNumber(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				if (extensionRegistry == null) {
					throw new NullPointerException();
				}
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0:
								done = true;
								break;
							default: {
								if (!parseUnknownFieldProto3(
										input, unknownFields, extensionRegistry, tag)) {
									done = true;
								}
								break;
							}
							case 10: {
								String s = input.readStringRequireUtf8();

								number_ = s;
								break;
							}
							case 16: {
								int rawValue = input.readEnum();

								type_ = rawValue;
								break;
							}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(
							e).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return PersonProtos.internal_static_Person_PhoneNumber_descriptor;
			}

			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return PersonProtos.internal_static_Person_PhoneNumber_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								PersonProtos.Person.PhoneNumber.class,
								PersonProtos.Person.PhoneNumber.Builder.class);
			}

			public static final int NUMBER_FIELD_NUMBER = 1;
			private volatile Object number_;

			/**
			 * <code>string number = 1;</code>
			 */
			public String getNumber() {
				Object ref = number_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					number_ = s;
					return s;
				}
			}

			/**
			 * <code>string number = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getNumberBytes() {
				Object ref = number_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					number_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int TYPE_FIELD_NUMBER = 2;
			private int type_;

			/**
			 * <code>.Person.PhoneType type = 2;</code>
			 */
			public int getTypeValue() {
				return type_;
			}

			/**
			 * <code>.Person.PhoneType type = 2;</code>
			 */
			public PersonProtos.Person.PhoneType getType() {
				PersonProtos.Person.PhoneType result = PersonProtos.Person.PhoneType.valueOf(type_);
				return result == null ? PersonProtos.Person.PhoneType.UNRECOGNIZED : result;
			}

			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1) {
					return true;
				}
				if (isInitialized == 0) {
					return false;
				}

				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output)
					throws java.io.IOException {
				if (!getNumberBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
				}
				if (type_ != PersonProtos.Person.PhoneType.MOBILE.getNumber()) {
					output.writeEnum(2, type_);
				}
				unknownFields.writeTo(output);
			}

			public int getSerializedSize() {
				int size = memoizedSize;
				if (size != -1) {
					return size;
				}

				size = 0;
				if (!getNumberBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
				}
				if (type_ != PersonProtos.Person.PhoneType.MOBILE.getNumber()) {
					size += com.google.protobuf.CodedOutputStream
							.computeEnumSize(2, type_);
				}
				size += unknownFields.getSerializedSize();
				memoizedSize = size;
				return size;
			}

			@Override
			public boolean equals(final Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof PersonProtos.Person.PhoneNumber)) {
					return super.equals(obj);
				}
				PersonProtos.Person.PhoneNumber other = (PersonProtos.Person.PhoneNumber) obj;

				boolean result = true;
				result = result && getNumber()
						.equals(other.getNumber());
				result = result && type_ == other.type_;
				result = result && unknownFields.equals(other.unknownFields);
				return result;
			}

			@Override
			public int hashCode() {
				if (memoizedHashCode != 0) {
					return memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + getDescriptor().hashCode();
				hash = (37 * hash) + NUMBER_FIELD_NUMBER;
				hash = (53 * hash) + getNumber().hashCode();
				hash = (37 * hash) + TYPE_FIELD_NUMBER;
				hash = (53 * hash) + type_;
				hash = (29 * hash) + unknownFields.hashCode();
				memoizedHashCode = hash;
				return hash;
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					java.nio.ByteBuffer data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					java.nio.ByteBuffer data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					com.google.protobuf.ByteString data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static PersonProtos.Person.PhoneNumber parseDelimitedFrom(
					java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input);
			}

			public static PersonProtos.Person.PhoneNumber parseDelimitedFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					com.google.protobuf.CodedInputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static PersonProtos.Person.PhoneNumber parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder() {
				return DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(PersonProtos.Person.PhoneNumber prototype) {
				return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return this == DEFAULT_INSTANCE
						? new Builder() : new Builder().mergeFrom(this);
			}

			@Override
			protected Builder newBuilderForType(
					BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code Person.PhoneNumber}
			 */
			public static final class Builder extends
					com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
					// @@protoc_insertion_point(builder_implements:Person.PhoneNumber)
					PersonProtos.Person.PhoneNumberOrBuilder {

				public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
					return PersonProtos.internal_static_Person_PhoneNumber_descriptor;
				}

				protected FieldAccessorTable
				internalGetFieldAccessorTable() {
					return PersonProtos.internal_static_Person_PhoneNumber_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									PersonProtos.Person.PhoneNumber.class,
									PersonProtos.Person.PhoneNumber.Builder.class);
				}

				// Construct using com.htzhu.protobuf.PersonProtos.Person.PhoneNumber.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(
						BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3
							.alwaysUseFieldBuilders) {
					}
				}

				public Builder clear() {
					super.clear();
					number_ = "";

					type_ = 0;

					return this;
				}

				public com.google.protobuf.Descriptors.Descriptor
				getDescriptorForType() {
					return PersonProtos.internal_static_Person_PhoneNumber_descriptor;
				}

				public PersonProtos.Person.PhoneNumber getDefaultInstanceForType() {
					return PersonProtos.Person.PhoneNumber.getDefaultInstance();
				}

				public PersonProtos.Person.PhoneNumber build() {
					PersonProtos.Person.PhoneNumber result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public PersonProtos.Person.PhoneNumber buildPartial() {
					PersonProtos.Person.PhoneNumber result = new PersonProtos.Person.PhoneNumber(
							this);
					result.number_ = number_;
					result.type_ = type_;
					onBuilt();
					return result;
				}

				public Builder clone() {
					return (Builder) super.clone();
				}

				public Builder setField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						Object value) {
					return (Builder) super.setField(field, value);
				}

				public Builder clearField(
						com.google.protobuf.Descriptors.FieldDescriptor field) {
					return (Builder) super.clearField(field);
				}

				public Builder clearOneof(
						com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return (Builder) super.clearOneof(oneof);
				}

				public Builder setRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						int index, Object value) {
					return (Builder) super.setRepeatedField(field, index, value);
				}

				public Builder addRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						Object value) {
					return (Builder) super.addRepeatedField(field, value);
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof PersonProtos.Person.PhoneNumber) {
						return mergeFrom((PersonProtos.Person.PhoneNumber) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(PersonProtos.Person.PhoneNumber other) {
					if (other == PersonProtos.Person.PhoneNumber.getDefaultInstance()) {
						return this;
					}
					if (!other.getNumber().isEmpty()) {
						number_ = other.number_;
						onChanged();
					}
					if (other.type_ != 0) {
						setTypeValue(other.getTypeValue());
					}
					this.mergeUnknownFields(other.unknownFields);
					onChanged();
					return this;
				}

				public final boolean isInitialized() {
					return true;
				}

				public Builder mergeFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
					PersonProtos.Person.PhoneNumber parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (PersonProtos.Person.PhoneNumber) e.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private Object number_ = "";

				/**
				 * <code>string number = 1;</code>
				 */
				public String getNumber() {
					Object ref = number_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						number_ = s;
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public com.google.protobuf.ByteString
				getNumberBytes() {
					Object ref = number_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(String) ref);
						number_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder setNumber(
						String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					number_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder clearNumber() {

					number_ = getDefaultInstance().getNumber();
					onChanged();
					return this;
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder setNumberBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					number_ = value;
					onChanged();
					return this;
				}

				private int type_ = 0;

				/**
				 * <code>.Person.PhoneType type = 2;</code>
				 */
				public int getTypeValue() {
					return type_;
				}

				/**
				 * <code>.Person.PhoneType type = 2;</code>
				 */
				public Builder setTypeValue(int value) {
					type_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>.Person.PhoneType type = 2;</code>
				 */
				public PersonProtos.Person.PhoneType getType() {
					PersonProtos.Person.PhoneType result = PersonProtos.Person.PhoneType
							.valueOf(type_);
					return result == null ? PersonProtos.Person.PhoneType.UNRECOGNIZED : result;
				}

				/**
				 * <code>.Person.PhoneType type = 2;</code>
				 */
				public Builder setType(PersonProtos.Person.PhoneType value) {
					if (value == null) {
						throw new NullPointerException();
					}

					type_ = value.getNumber();
					onChanged();
					return this;
				}

				/**
				 * <code>.Person.PhoneType type = 2;</code>
				 */
				public Builder clearType() {

					type_ = 0;
					onChanged();
					return this;
				}

				public final Builder setUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.setUnknownFieldsProto3(unknownFields);
				}

				public final Builder mergeUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.mergeUnknownFields(unknownFields);
				}

				// @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
			}

			// @@protoc_insertion_point(class_scope:Person.PhoneNumber)
			private static final PersonProtos.Person.PhoneNumber DEFAULT_INSTANCE;

			static {
				DEFAULT_INSTANCE = new PersonProtos.Person.PhoneNumber();
			}

			public static PersonProtos.Person.PhoneNumber getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			private static final com.google.protobuf.Parser<PhoneNumber>
					PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
				public PhoneNumber parsePartialFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new PhoneNumber(input, extensionRegistry);
				}
			};

			public static com.google.protobuf.Parser<PhoneNumber> parser() {
				return PARSER;
			}

			@Override
			public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
				return PARSER;
			}

			public PersonProtos.Person.PhoneNumber getDefaultInstanceForType() {
				return DEFAULT_INSTANCE;
			}

		}

		public static final int NAME_FIELD_NUMBER = 1;
		private volatile Object name_;

		/**
		 * <code>string name = 1;</code>
		 */
		public String getName() {
			Object ref = name_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>string name = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getNameBytes() {
			Object ref = name_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int ID_FIELD_NUMBER = 2;
		private int id_;

		/**
		 * <code>int32 id = 2;</code>
		 */
		public int getId() {
			return id_;
		}

		public static final int EMAIL_FIELD_NUMBER = 3;
		private volatile Object email_;

		/**
		 * <code>string email = 3;</code>
		 */
		public String getEmail() {
			Object ref = email_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				email_ = s;
				return s;
			}
		}

		/**
		 * <code>string email = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getEmailBytes() {
			Object ref = email_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				email_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PHONE_FIELD_NUMBER = 4;
		private PersonProtos.Person.PhoneNumber phone_;

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		public boolean hasPhone() {
			return phone_ != null;
		}

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		public PersonProtos.Person.PhoneNumber getPhone() {
			return phone_ == null ? PersonProtos.Person.PhoneNumber.getDefaultInstance() : phone_;
		}

		/**
		 * <code>.Person.PhoneNumber phone = 4;</code>
		 */
		public PersonProtos.Person.PhoneNumberOrBuilder getPhoneOrBuilder() {
			return getPhone();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
			}
			if (id_ != 0) {
				output.writeInt32(2, id_);
			}
			if (!getEmailBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
			}
			if (phone_ != null) {
				output.writeMessage(4, getPhone());
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
			}
			if (id_ != 0) {
				size += com.google.protobuf.CodedOutputStream
						.computeInt32Size(2, id_);
			}
			if (!getEmailBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
			}
			if (phone_ != null) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(4, getPhone());
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof PersonProtos.Person)) {
				return super.equals(obj);
			}
			PersonProtos.Person other = (PersonProtos.Person) obj;

			boolean result = true;
			result = result && getName()
					.equals(other.getName());
			result = result && (getId()
					== other.getId());
			result = result && getEmail()
					.equals(other.getEmail());
			result = result && (hasPhone() == other.hasPhone());
			if (hasPhone()) {
				result = result && getPhone()
						.equals(other.getPhone());
			}
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + ID_FIELD_NUMBER;
			hash = (53 * hash) + getId();
			hash = (37 * hash) + EMAIL_FIELD_NUMBER;
			hash = (53 * hash) + getEmail().hashCode();
			if (hasPhone()) {
				hash = (37 * hash) + PHONE_FIELD_NUMBER;
				hash = (53 * hash) + getPhone().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static PersonProtos.Person parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static PersonProtos.Person parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static PersonProtos.Person parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static PersonProtos.Person parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static PersonProtos.Person parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static PersonProtos.Person parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static PersonProtos.Person parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static PersonProtos.Person parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static PersonProtos.Person parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static PersonProtos.Person parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static PersonProtos.Person parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static PersonProtos.Person parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(PersonProtos.Person prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code Person}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:Person)
				PersonProtos.PersonOrBuilder {

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return PersonProtos.internal_static_Person_descriptor;
			}

			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return PersonProtos.internal_static_Person_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								PersonProtos.Person.class, PersonProtos.Person.Builder.class);
			}

			// Construct using com.htzhu.protobuf.PersonProtos.Person.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				name_ = "";

				id_ = 0;

				email_ = "";

				if (phoneBuilder_ == null) {
					phone_ = null;
				} else {
					phone_ = null;
					phoneBuilder_ = null;
				}
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return PersonProtos.internal_static_Person_descriptor;
			}

			public PersonProtos.Person getDefaultInstanceForType() {
				return PersonProtos.Person.getDefaultInstance();
			}

			public PersonProtos.Person build() {
				PersonProtos.Person result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public PersonProtos.Person buildPartial() {
				PersonProtos.Person result = new PersonProtos.Person(this);
				result.name_ = name_;
				result.id_ = id_;
				result.email_ = email_;
				if (phoneBuilder_ == null) {
					result.phone_ = phone_;
				} else {
					result.phone_ = phoneBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof PersonProtos.Person) {
					return mergeFrom((PersonProtos.Person) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(PersonProtos.Person other) {
				if (other == PersonProtos.Person.getDefaultInstance()) {
					return this;
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (other.getId() != 0) {
					setId(other.getId());
				}
				if (!other.getEmail().isEmpty()) {
					email_ = other.email_;
					onChanged();
				}
				if (other.hasPhone()) {
					mergePhone(other.getPhone());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				PersonProtos.Person parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (PersonProtos.Person) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object name_ = "";

			/**
			 * <code>string name = 1;</code>
			 */
			public String getName() {
				Object ref = name_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string name = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getNameBytes() {
				Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string name = 1;</code>
			 */
			public Builder setName(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 1;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 1;</code>
			 */
			public Builder setNameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private int id_;

			/**
			 * <code>int32 id = 2;</code>
			 */
			public int getId() {
				return id_;
			}

			/**
			 * <code>int32 id = 2;</code>
			 */
			public Builder setId(int value) {

				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int32 id = 2;</code>
			 */
			public Builder clearId() {

				id_ = 0;
				onChanged();
				return this;
			}

			private Object email_ = "";

			/**
			 * <code>string email = 3;</code>
			 */
			public String getEmail() {
				Object ref = email_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					email_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getEmailBytes() {
				Object ref = email_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					email_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder setEmail(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				email_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder clearEmail() {

				email_ = getDefaultInstance().getEmail();
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder setEmailBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				email_ = value;
				onChanged();
				return this;
			}

			private PersonProtos.Person.PhoneNumber phone_ = null;
			private com.google.protobuf.SingleFieldBuilderV3<
					PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> phoneBuilder_;

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public boolean hasPhone() {
				return phoneBuilder_ != null || phone_ != null;
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public PersonProtos.Person.PhoneNumber getPhone() {
				if (phoneBuilder_ == null) {
					return phone_ == null ? PersonProtos.Person.PhoneNumber.getDefaultInstance()
							: phone_;
				} else {
					return phoneBuilder_.getMessage();
				}
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public Builder setPhone(PersonProtos.Person.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					phone_ = value;
					onChanged();
				} else {
					phoneBuilder_.setMessage(value);
				}

				return this;
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public Builder setPhone(
					PersonProtos.Person.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					phone_ = builderForValue.build();
					onChanged();
				} else {
					phoneBuilder_.setMessage(builderForValue.build());
				}

				return this;
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public Builder mergePhone(PersonProtos.Person.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (phone_ != null) {
						phone_ =
								PersonProtos.Person.PhoneNumber.newBuilder(phone_).mergeFrom(value)
										.buildPartial();
					} else {
						phone_ = value;
					}
					onChanged();
				} else {
					phoneBuilder_.mergeFrom(value);
				}

				return this;
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public Builder clearPhone() {
				if (phoneBuilder_ == null) {
					phone_ = null;
					onChanged();
				} else {
					phone_ = null;
					phoneBuilder_ = null;
				}

				return this;
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public PersonProtos.Person.PhoneNumber.Builder getPhoneBuilder() {

				onChanged();
				return getPhoneFieldBuilder().getBuilder();
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			public PersonProtos.Person.PhoneNumberOrBuilder getPhoneOrBuilder() {
				if (phoneBuilder_ != null) {
					return phoneBuilder_.getMessageOrBuilder();
				} else {
					return phone_ == null ?
							PersonProtos.Person.PhoneNumber.getDefaultInstance() : phone_;
				}
			}

			/**
			 * <code>.Person.PhoneNumber phone = 4;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<
					PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>
			getPhoneFieldBuilder() {
				if (phoneBuilder_ == null) {
					phoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
							PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>(
							getPhone(),
							getParentForChildren(),
							isClean());
					phone_ = null;
				}
				return phoneBuilder_;
			}

			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:Person)
		}

		// @@protoc_insertion_point(class_scope:Person)
		private static final PersonProtos.Person DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new PersonProtos.Person();
		}

		public static PersonProtos.Person getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Person>
				PARSER = new com.google.protobuf.AbstractParser<Person>() {
			public Person parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Person(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Person> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<Person> getParserForType() {
			return PARSER;
		}

		public PersonProtos.Person getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Person_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_Person_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Person_PhoneNumber_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_Person_PhoneNumber_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\022PersonProtos.proto\"\302\001\n\006Person\022\014\n\004name\030" +
						"\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022\"\n\005phon"
						+
						"e\030\004 \001(\0132\023.Person.PhoneNumber\032>\n\013PhoneNum" +
						"ber\022\016\n\006number\030\001 \001(\t\022\037\n\004type\030\002 \001(\0162\021.Pers"
						+
						"on.PhoneType\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n" +
						"\004HOME\020\001\022\010\n\004WORK\020\002B\"\n\022com.htzhu.protobufB" +
						"\014PersonProtosb\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						}, assigner);
		internal_static_Person_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_Person_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Person_descriptor,
				new String[]{"Name", "Id", "Email", "Phone",});
		internal_static_Person_PhoneNumber_descriptor =
				internal_static_Person_descriptor.getNestedTypes().get(0);
		internal_static_Person_PhoneNumber_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Person_PhoneNumber_descriptor,
				new String[]{"Number", "Type",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
