// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.htzhu.protobuf.student;

public interface MyRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:com.htzhu.protobuf.student.MyRequest)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string username = 1;</code>
	 */
	java.lang.String getUsername();

	/**
	 * <code>string username = 1;</code>
	 */
	com.google.protobuf.ByteString
	getUsernameBytes();
}
