// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.htzhu.protobuf.student;

public final class StudentProto {

	private StudentProto() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor
			internal_static_com_htzhu_protobuf_student_MyRequest_descriptor;
	static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_com_htzhu_protobuf_student_MyRequest_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor
			internal_static_com_htzhu_protobuf_student_MyResponse_descriptor;
	static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_com_htzhu_protobuf_student_MyResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		java.lang.String[] descriptorData = {
				"\n\rStudent.proto\022\032com.htzhu.protobuf.stud" +
						"ent\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMy" +
						"Response\022\020\n\010realname\030\002 \001(\t2z\n\016StudentSer" +
						"vice\022h\n\025GetRealNameByUsername\022%.com.htzh" +
						"u.protobuf.student.MyRequest\032&.com.htzhu" +
						".protobuf.student.MyResponse\"\000B,\n\032com.ht" +
						"zhu.protobuf.studentB\014StudentProtoP\001b\006pr" +
						"oto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						}, assigner);
		internal_static_com_htzhu_protobuf_student_MyRequest_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_com_htzhu_protobuf_student_MyRequest_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_htzhu_protobuf_student_MyRequest_descriptor,
				new java.lang.String[]{"Username",});
		internal_static_com_htzhu_protobuf_student_MyResponse_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_com_htzhu_protobuf_student_MyResponse_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_htzhu_protobuf_student_MyResponse_descriptor,
				new java.lang.String[]{"Realname",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
