// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_streaming.proto

package com.htzhu.protobuf.hellostream;

public final class HelloStreamingProto {

	private HelloStreamingProto() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor
			internal_static_com_htzhu_protobuf_hellostream_HelloRequest_descriptor;
	static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_com_htzhu_protobuf_hellostream_HelloRequest_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor
			internal_static_com_htzhu_protobuf_hellostream_HelloReply_descriptor;
	static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_com_htzhu_protobuf_hellostream_HelloReply_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		java.lang.String[] descriptorData = {
				"\n\025hello_streaming.proto\022\036com.htzhu.proto" +
						"buf.hellostream\"\034\n\014HelloRequest\022\014\n\004name\030" +
						"\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2\207\001\n"
						+
						"\020StreamingGreeter\022s\n\021SayHelloStreaming\022," +
						".com.htzhu.protobuf.hellostream.HelloReq" +
						"uest\032*.com.htzhu.protobuf.hellostream.He" +
						"lloReply\"\000(\0010\001B>\n\036com.htzhu.protobuf.hel" +
						"lostreamB\023HelloStreamingProtoP\001\242\002\004HLWSb\006" +
						"proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						}, assigner);
		internal_static_com_htzhu_protobuf_hellostream_HelloRequest_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_com_htzhu_protobuf_hellostream_HelloRequest_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_htzhu_protobuf_hellostream_HelloRequest_descriptor,
				new java.lang.String[]{"Name",});
		internal_static_com_htzhu_protobuf_hellostream_HelloReply_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_com_htzhu_protobuf_hellostream_HelloReply_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_htzhu_protobuf_hellostream_HelloReply_descriptor,
				new java.lang.String[]{"Message",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
